[features]
seeds = false
skip-lint = false
[programs.localnet]
swapverse = "AeFLgMmKmVjLUv4jBGjXsrNf4MKPaVate5fNmqrDDoin"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/satyam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
